In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.14.0


## Load a dataset

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [5]:
y_train_n = tf.keras.utils.to_categorical(y_train, num_classes=10)
y_test_n = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [12]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'],
              run_eagerly=True)

In [13]:
model.fit(x_train, y_train_n, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 42s 22ms/step - loss: 0.2914 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 42s 22ms/step - loss: 0.1397 - accuracy: 0.9589
Epoch 3/5
1875/1875 [==============================] - 43s 23ms/step - loss: 0.1047 - accuracy: 0.9676
Epoch 4/5
1875/1875 [==============================] - 42s 22ms/step - loss: 0.0863 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 41s 22ms/step - loss: 0.0723 - accuracy: 0.9771


In [14]:
model.evaluate(x_test,  y_test_n, verbose=2)

313/313 - 4s - loss: 0.0713 - accuracy: 0.9777 - 4s/epoch - 12ms/step


[0.07134872674942017, 0.9776999950408936]

In [15]:
y_test_n[12]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [16]:
x_test[10].shape

(28, 28)

In [17]:
test_sample = x_test[12].reshape(1,28,28)

In [18]:
model.predict(test_sample)

1/1 [==============================] - 0s 34ms/step


array([[-10.67532   ,  -8.514549  ,  -6.4570613 ,  -1.5410538 ,
          2.4699686 ,  -2.618428  , -14.524479  ,  -0.48620337,
         -3.4566853 ,  10.406761  ]], dtype=float32)

In [19]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [20]:
probability_model.predict(test_sample)

1/1 [==============================] - 0s 67ms/step


array([[6.9823425e-10, 6.0591518e-09, 4.7420631e-08, 6.4708665e-06,
        3.5721314e-04, 2.2032546e-06, 1.4870740e-11, 1.8581393e-05,
        9.5282769e-07, 9.9961448e-01]], dtype=float32)